#!/usr/bin/env ruby

require_relative './lib/boot'
require 'daemons'

Daemons.run_proc(File.basename(__FILE__), {:dir => File.dirname(__FILE__)}) do
  require_relative './lib/robotito'
  Signal.trap('INT') { Robotito.stop }
  Robotito.run
end
